### ISSUE TITLE
Removing [TTT Weight System] is up to date (1.0.1)?

### ISSUE THREAD

**Issue by dpaci** [lzinga/TTTWeightedTraitorSelection#10]
Hey, I've been using the addon for quite a while now, I updated it and now I can't remove that message I get everytime I connect. It's not annoying, but I just don't want it. I tried looking in the files for anything like it, but I just can't find how to remove it.

How can I remove that message? Thanks for reading.

**Comment by MinIsMin** [comment]
You can remove it by removing the lines 108-110 in `weightsystem_autorun.lua`.
https://github.com/lzinga/TTTWeightedTraitorSelection/blob/62f1b296722c3f71af6737054d107e14627d25eb/tttweightsystem/lua/autorun/weightsystem_autorun.lua#L108-L110

Since the license is MIT you're allowed to do so.

**Comment by dpaci** [comment]
Perfect, thanks a lot!
