### ISSUE TITLE
Seemingly bizzare calculations

### ISSUE THREAD

**Issue by chiachichang** [lzinga/TTTWeightedTraitorSelection#17]
I apologize for my lack of ability to be more clear about this, however, the weights seem to be changing midround and the percentages seem to be completely random. Each time a percentage is generated on the weight log or with the chat command, it is completely different with seemingly no order. I have used a clean install with no changes.

**Comment by lzinga** [comment]
When you say mid-round do you mean like you would be in the middle of a round with roles already selected and the amount would change?

**Comment by chiachichang** [comment]
That is correct, the chat occasionally has the (Your next round to be a traitor is x%) and this value changes as the round goes on. Also, I have heard from players that the longer they are not traitor the lower the percentage is.

**Comment by ghost** [comment]
This is has been an issue for quite a while

**Comment by HerrmannMax** [comment]
Can this issue be closed due to the changes from the merge of https://github.com/lzinga/TTTWeightedTraitorSelection/pull/20 ?
