### ISSUE TITLE
Broken Weight System

### ISSUE THREAD

**Issue by FappyMcFap** [lzinga/TTTWeightedTraitorSelection#19]
As another user has mentioned below, the traitor chance changes throughout the rounds. Also, everyones weight is just stuck at 5. It doesn't change at all from that. 

Edit: Once the weight has been set once it stays to that.

**Comment by lzinga** [comment]
I don't know what you are talking about "another user has mentioned below", how about comment in that one or thumbs up it instead?

Going to close this out, feel free to upvote or add in your comments in the issue you are talking about.
