### ISSUE TITLE
Round Preparing Error

### ISSUE THREAD

**Issue by ForeverButthurt** [lzinga/TTTWeightedTraitorSelection#2]
When preparing end i have this error :
[ERROR] addons/tttweightsystem/lua/weightsystem/sh_playerweight.lua:110: bad argument #1 to 'WriteUInt' (number expected, got nil)
1. WriteUInt - [C]:-1
   1. SendWeightInfo - addons/tttweightsystem/lua/weightsystem/sh_playerweight.lua:110
   2. func - addons/tttweightsystem/lua/weightsystem/sh_playerweight.lua:92
      1. unknown - lua/includes/extensions/net.lua:32

**Comment by lzinga** [comment]
This doesn't work with bots which I am assuming you are running it with as thats the only time ive ever seen this problem occur.

**Comment by ForeverButthurt** [comment]
okay but now i have another one 
[ERROR] addons/tttweightsystem/lua/weightsystem/sv_init.lua:84: attempt to perform arithmetic on a nil value
1. SelectPlayerForTraitor - addons/tttweightsystem/lua/weightsystem/sv_init.lua:84
   1. oldselect - addons/tttweightsystem/lua/weightsystem/sv_init.lua:180
   2. SelectRoles - addons/wyozitev/lua/sv_wtev_tttoverrides.lua:72
      1. old_BeginRound - gamemodes/terrortown/gamemode/init.lua:662
      2. unknown - addons/deathmatch/lua/sv_specdm_overrides.lua:205

**Comment by lzinga** [comment]
That looks like it might not be creating the tables in the database. Do you have the config and proper connection to the database?
