### ISSUE TITLE
Get a script error when opening the game.

### ISSUE THREAD

**Issue by Aljaden** [lzinga/TTTWeightedTraitorSelection#21]
When I open the game, a message pops up telling that there's been some king of script error.
Inspecting the console for further information this error report is shown:
![ttt error](https://user-images.githubusercontent.com/64442867/80433112-548bc580-88f6-11ea-83dd-ffe588993f89.JPG)

NOTE: I'm not playing on a server. I use the "begin a game and use connect (my ip) on the console" to play with my friends via Hamachi. Not sure if that is a problem.

**Comment by HerrmannMax** [comment]
I think this could be a problem that you use hamachi and not the official way...
The code here uses the https://wiki.facepunch.com/gmod/Player:SteamID64 or https://wiki.facepunch.com/gmod/util.SteamIDFrom64 functions to get the steamIDs and write them into the table to map the calculations to the players
If you are not connected to any steam server and cant get a valid steamID then I dont think this mod can be used for you...

Maybe this guide can help you to set up a dedicaded server:
https://steamcommunity.com/sharedfiles/filedetails/?id=1315710212
he also recoreded it on video:
https://www.youtube.com/watch?v=qPoAJ835Fp0&list=PL5Wv_6qhYVzlpNa7j1mTYSab8j63x_MaY&index=1

**Comment by Aljaden** [comment]
Thanks for the answer. I setup a server and it seemed that there was another problem and not the problem I had without the server. In fact, my problem was that is was stupid enough to not change the gamemode of the server, so testing with my friends I decided to change the gamemode for some otrher reason and it worked perfectly.
In conclusion, there was no problem and I was the one doing things wrong. On the bightside, I now have a fully functioning server and I can happily play with my friends with a fair Traitor Selection algorithm.
Much love.
