### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by MinIsMin** [lzinga/TTTWeightedTraitorSelection#5]
With this addon (latest changes) installed, my server won't start.
It stops after the include of TTT language files.
No commands or cvar can be used in the console.

Without the addon it works fine.
I looked into the code but couldn't find the error.
Last message from [TTT WeightSystem] is Loading with SQLite.

**Comment by lzinga** [comment]
mentioning @LaurenceKaye as he was the one who added the SQLite, I haven't messed with the code for this in a while.

Based on the limited info here I would assume it has something to do with the loading of SQLite since it never makes it past it. Possibly the SQLite config or something along those lines?

**Comment by LaurenceKaye** [comment]
I'm without my PC for this week but I'll take a look as soon as I can. In the meantime there is a config option to switch it back to mysql.

**Comment by MinIsMin** [comment]
I should add, that my OS is Ubuntu 14.04.

**Comment by LaurenceKaye** [comment]
Did switching it back to MySQL work? I've been trying to replicate this issue and have thus far been unable to.

If it works when in MySQL mode, then at least I can narrow my search to the SQLite code.

Thanks

**Comment by MinIsMin** [comment]
I installed the newest versions of gmsv_mysqloo and libmysqlclient (Linux) and the following occured:

```
[TTT WeightSystem] Could not find database.txt file.
[TTT WeightSystem] Group Permissions Found.
[TTT WeightSystem] Version 1.0.12 is loading..
[TTT WeightSystem] Loading with MySQL.

[ERROR] addons/tttweightsystem/lua/weightsystem/sv_database_mysql.lua:15: attempt to index field 'Database' (a nil value)
  1. unknown - addons/tttweightsystem/lua/weightsystem/sv_database_mysql.lua:15
   2. include - [C]:-1
    3. unknown - addons/tttweightsystem/lua/weightsystem/sv_database.lua:13
     4. include - [C]:-1
      5. unknown - addons/tttweightsystem/lua/weightsystem/sv_init.lua:5
       6. include - [C]:-1
        7. unknown - addons/tttweightsystem/lua/autorun/weightsystem_autorun.lua:72
```

**Comment by LaurenceKaye** [comment]
Looks like database.txt (which contains the database connection details) wasn't found or created which is what has caused the later errors to occur. We should probably add something to check the details are present before it tries to connect to the database.

Does the data directory have write access?

**Comment by LaurenceKaye** [comment]
Nevermind that, I just remembered that the database.txt file has to be created by you based on database-template.txt

Did you upgrade to this version from an older version? If so, it seems odd that database.txt wouldn't already exist for you as MySQL was the only available option before

**Comment by MinIsMin** [comment]
Ah my bad, I didn't thought of writing "database.txt"

Same problem as first post (stops after the include of TTT language files), with MySQL. No Lua error.

**Comment by LaurenceKaye** [comment]
Could you post a copy of the console output from just before the addon to just after it stops?

Thanks

**Comment by MinIsMin** [comment]
Because GitHub thinks, there are too many line ends: http://pastebin.com/7HXLUVd3

**Comment by LaurenceKaye** [comment]
I'll make a new version tonight with more console printing, primarily just to see if we can get more information on exactly where it's encountering the issue.

**Comment by MinIsMin** [comment]
That would be good.
As far as I now, it fully parses everyhting before and sv_database_sqlite.lua.
After that, it gets stuck.

**Comment by MinIsMin** [comment]
@LaurenceKaye Did you already upload the new test version?

**Comment by MinIsMin** [comment]
Is there any news? I couldn't find the error.

**Comment by LaurenceKaye** [comment]
Sorry for the delay, I had computer issues last month that have now lead to me getting a new laptop last week. Still in the process of getting my dev environment set up again but I'll be getting you an update as soon as I can!

Just wanted to drop you a comment so you don't think I'm ignoring you :)
