### ISSUE TITLE
SetDetectiveCount not called

### ISSUE THREAD

**Issue by MinIsMin** [lzinga/TTTWeightedTraitorSelection#8]
When being selected as detective the detective counter isn't called but round counter.

![wef](https://cloud.githubusercontent.com/assets/18466226/21073746/81b46ba2-bee7-11e6-940f-495a8f8b077d.jpg)

`print("Detective Count: " .. det_count)` shows the correct detective count.

**Comment by lzinga** [comment]
so `print("Detective Count: " .. det_count)` is printing into server console how many detectives are expected for the round. The menu you are showing is each players information on how many times they have played and how many times they have been each role.

Not sure if I fully understand, apart from maybe that you were selected as Detective in that picture and the count didn't go up for you. Could you please expand on what is happening?

**Comment by MinIsMin** [comment]
The "Detective" count isn't going up when I'm selected as detective.
The image shows that I played 4 rounds but played only two times as Innocent.
The two Detective count's are missing there.

I think, there's an error (maybe during SQL) saving the data (which can be accessed and looks like the image).

**Comment by lzinga** [comment]
Did you force yourself as detective?

**Comment by monster010** [comment]
#12 that should solve the problem. =)
